using System;
using System.Collections.Generic;

namespace Standing_Order_Vat_App.DAL.GB_Register
{
    public partial class Cif
    {
        public string? Cif1 { get; set; }
        public string? FamilyMemberName1 { get; set; }
        public string? FamilyMemberName2 { get; set; }
        public string? FamilyMemberName3 { get; set; }
        public string? FamilyMemberName4 { get; set; }
        public string? FamilyMemberName5 { get; set; }
        public string? FmlyMbr1BDay { get; set; }
        public string? FmlyMbr2BDay { get; set; }
        public string? FmlyMbr3BDay { get; set; }
        public string? FmlyMbr4BDay { get; set; }
        public string? FmlyMbr5BDay { get; set; }
        public string? Relationship1 { get; set; }
        public string? Relationship2 { get; set; }
        public string? Relationship3 { get; set; }
        public string? Relationship4 { get; set; }
        public string? Relationship5 { get; set; }
        public string? MessageNote1 { get; set; }
        public string? MessageNote2 { get; set; }
        public string? MessageNote3 { get; set; }
        public string? Birthdate { get; set; }
        public string? BirthMonthDate { get; set; }
        public string? EmployerName { get; set; }
        public string? SicCode { get; set; }
        public string? JobTitle { get; set; }
        public string? Salary { get; set; }
        public string? Education { get; set; }
        public string? BrokerageAccount { get; set; }
        public string? FinancialPlanning { get; set; }
        public string? CreditLine { get; set; }
        public string? WorkPhone { get; set; }
        public string? _2ndLoanOfficer { get; set; }
        public string? LoanRatingCode { get; set; }
        public string? LoansMadeThisYear { get; set; }
        public string? TimePastDue3060 { get; set; }
        public string? PastDue6090 { get; set; }
        public string? PastDue90 { get; set; }
        public string? FinancialStmtDate { get; set; }
        public string? TotalAssets { get; set; }
        public string? NetWorth { get; set; }
        public string? HighLoanBalance { get; set; }
        public string? LowLoanBalance { get; set; }
        public string? YtdCoupons { get; set; }
        public string? YtdDividend { get; set; }
        public string? YtdBondInte { get; set; }
        public string? Date1 { get; set; }
        public string? Description1 { get; set; }
        public string? Date2 { get; set; }
        public string? Description2 { get; set; }
        public string? Date3 { get; set; }
        public string? Description3 { get; set; }
        public string? Date4 { get; set; }
        public string? Description4 { get; set; }
        public string? Date5 { get; set; }
        public string? Description5 { get; set; }
        public string? BankSharsHe { get; set; }
        public string? NumberOfVot { get; set; }
        public string? DateLastDividend { get; set; }
        public string? AmountLastD { get; set; }
        public string? DivCorresAcctType { get; set; }
        public string? DivCorresAcct { get; set; }
        public string? ExcludeFromSysGen { get; set; }
        public string? AmountOfFix { get; set; }
        public string? CensusTract { get; set; }
        public string? YtdDivIntH { get; set; }
        public string? CifCreditLimit { get; set; }
        public string? CifDepositBalance { get; set; }
        public string? CifLoanBalance { get; set; }
        public string? CifTotalCommitted { get; set; }
        public string? CifUnusedCommit { get; set; }
        public string? RelatedDepositBal { get; set; }
        public string? RelatedLoanBal { get; set; }
        public string? RelatedCifCommit { get; set; }
        public string? RelatedUnusedComm { get; set; }
        public string? CreditCardBalance { get; set; }
        public string? CreditCardLimit { get; set; }
        public string? OrigCustomerDate { get; set; }
        public string? YearsAsCustomer { get; set; }
        public string? RevenuePerAnalysis { get; set; }
        public string? ExpensePerAnalysis { get; set; }
        public string? ProfitFromAnalysis { get; set; }
        public string? NumericalRanking { get; set; }
        public string? PercentileRanking { get; set; }
        public string? RevenuePriorYear { get; set; }
        public string? ExpensesPriorYear { get; set; }
        public string? ProfitPriorYear { get; set; }
        public string? NumericalRankPyr { get; set; }
        public string? PercentileRankPyr { get; set; }
        public string? RevenuePrevYr { get; set; }
        public string? ExpensesPrevYr { get; set; }
        public string? ProfitPrevYr { get; set; }
        public string? NumRankingPrevYr { get; set; }
        public string? PrcntRankPrevYr { get; set; }
        public string? EMailAddress { get; set; }
        public string? MajorCredLineFlg { get; set; }
        public string? AmountOrigCommit { get; set; }
        public string? AmtRemainToAdv { get; set; }
        public string? IntReducesAvail { get; set; }
        public string? LtChgReduceAvail { get; set; }
        public string? AdvanceEndingDate { get; set; }
        public string? MajorLineSecured { get; set; }
        public string? TotBalAllTiedLns { get; set; }
        public string? TotIencTiedLoans { get; set; }
        public string? TotUnpaidLa { get; set; }
        public string? TiedLoanFirstDue { get; set; }
        public string? AmtPDAllTiedLns { get; set; }
        public string? DealerFloorPlan { get; set; }
        public string? FpPrinBillNotPd { get; set; }
        public string? FpIntBillNotPd { get; set; }
        public string? CipIdentType { get; set; }
        public string? CipIdNumber { get; set; }
        public string? CipIdIssuer { get; set; }
        public string? DateIdIssued { get; set; }
        public string? DateIdExpires { get; set; }
        public string? CustomerMarketing { get; set; }
        public string? AffiliateExpDate { get; set; }
        public string? AffilOptOutCode { get; set; }
        public string? AffilOptOutDate { get; set; }
        public string? BalSheetStmtDate { get; set; }
        public string? HistCashStmtDate { get; set; }
        public string? IncomeStmtDate { get; set; }
        public string? ProjCashStmtDate { get; set; }
        public string? PersonalStmtDate { get; set; }
        public string? TaxReturnDate { get; set; }
        public string? BalSheetDueDate { get; set; }
        public string? HistCashDueDate { get; set; }
        public string? IncStmtDueDate { get; set; }
        public string? ProjCashDueDate { get; set; }
        public string? PersStmtDueDate { get; set; }
        public string? TaxReturnDueDate { get; set; }
        public string? ThresholdAmount { get; set; }
        public string? CifMemoposteDrs { get; set; }
        public string? CifMemoposteCrs { get; set; }
        public string? IndirectDepBal { get; set; }
        public string? IndirectLoanBal { get; set; }
        public string? IndirectCommitted { get; set; }
        public string? IndirectUnusedCom { get; set; }
        public string? FirstDateNoRec { get; set; }
        public string? ExcludeAutoDel { get; set; }
        public string? BankDividend { get; set; }
        public string? HoldCoDivF { get; set; }
        public string? ParticLoanBal { get; set; }
        public string? ParticCommitted { get; set; }
        public string? ParticUnusedCom { get; set; }
        public string? DebtIncomeRatio { get; set; }
        public string? TaxExemptInterest { get; set; }
        public string? PrivateActBondInt { get; set; }
        public string? DepositWeightedAvg { get; set; }
        public string? LoanWeightedAvg { get; set; }
        public string? AmountDueAl { get; set; }
        public string? YtdIntEarnedDep { get; set; }
        public string? YtdIntPaidDep { get; set; }
        public string? PyrIntEarnedDep { get; set; }
        public string? PyrIntPaidDep { get; set; }
        public string? YtdIntEarnedLoan { get; set; }
        public string? YtdIntPaidLoan { get; set; }
        public string? PyrIntEarnedLoan { get; set; }
        public string? PyrIntPaidLoans { get; set; }
        public string? Occupation { get; set; }
        public string? _2ndAddrIndicator { get; set; }
        public string? CifDdaBalance { get; set; }
        public string? CifSavingsBalance { get; set; }
        public string? CifCdBalance { get; set; }
        public string? CifIraBalance { get; set; }
        public string? BankruptcyStatus { get; set; }
        public string? BankruptcyType { get; set; }
        public string? BankruptcyCaseNbr { get; set; }
        public string? BkrptcyDischrgeDt { get; set; }
        public string? NetTellerUser { get; set; }
        public string? NtCashMgmtUser { get; set; }
        public string? JhaBillPayUser { get; set; }
        public string? ElectronicStmts { get; set; }
        public string? PassPortCustomer { get; set; }
        public string? DtLastAddrChange { get; set; }
        public string? EstIrsIntPdYtd { get; set; }
        public string? EstIrsInRcvdYtd { get; set; }
        public string? EstIrsIntPdPyr { get; set; }
        public string? EstIrsIntRcvdPyr { get; set; }
        public string? NtAoeAttempts { get; set; }
        public string? PrimaryCifAccount { get; set; }
        public string? SharesAsOf { get; set; }
        public string? PhoneOrder { get; set; }
        public string? TotalCollCalculatd { get; set; }
        public string? TotalCollManual { get; set; }
        public string? LtvTotalCalculatd { get; set; }
        public string? LtvTotalManual { get; set; }
        public string? CifPayoffUnsecurd { get; set; }
        public string? CifCommittedUnsecr { get; set; }
        public string? BankDivsExempt { get; set; }
        public string? HCDivsExempt { get; set; }
        public string? CustomerStatus { get; set; }
        public string? _10Sharehold { get; set; }
        public string? CountryOfBirth { get; set; }
        public string? CountryOfWork { get; set; }
        public string? AltCtznshpCntry1 { get; set; }
        public string? IdAltCtzspCnty1 { get; set; }
        public string? AltCtznshpCntry2 { get; set; }
        public string? IdAltCtzspCnty2 { get; set; }
        public string? AltCtznshpCntry3 { get; set; }
        public string? IdAltCtzspCnty3 { get; set; }
        public string? AltCtznshpCntry4 { get; set; }
        public string? IdAltCtzspCnty4 { get; set; }
        public string? USPowerOfAttny { get; set; }
        public string? USStandingOrder { get; set; }
        public string? TaxId1SigDir { get; set; }
        public string? TaxId2SigDir { get; set; }
        public string? TaxId3SigDir { get; set; }
        public string? TaxId4SigDir { get; set; }
        public string? TaxId5SigDir { get; set; }
        public string? TaxId6SigDir { get; set; }
        public string? TaxId7SigDir { get; set; }
        public string? TaxId8SigDir { get; set; }
        public string? TaxId9SigDir { get; set; }
        public string? TaxId10SigDir { get; set; }
        public string? FatcaCurrCode { get; set; }
        public string? UsdCifAggDepBal { get; set; }
        public string? YtdHighCifAggBal { get; set; }
        public string? UsTaxIdCode { get; set; }
        public string? UsTaxIdNumber { get; set; }
        public string? FatcaAccountType { get; set; }
        public string? UsdCifAggrAvgBal { get; set; }
        public string? UsdCifAggrYtdInt { get; set; }
        public string? CurrentDivPaid { get; set; }
        public string? DatePaid { get; set; }
        public string? DateLstDevCashed { get; set; }
        public string? DividendCheck { get; set; }
        public string? Date1994DivCashed { get; set; }
        public string? CheckIssueStatus { get; set; }
        public string? Orig1SharesHeld { get; set; }
        public string? ConvOf5Shares { get; set; }
        public string? Tot1stBonusIssue { get; set; }
        public string? Tot2ndBonusIssue { get; set; }
        public string? Tot3rdBonusIssue { get; set; }
        public string? TotOriginalShares { get; set; }
        public string? PlaceOfBirt { get; set; }
        public string? Nationality { get; set; }
        public string? Employer { get; set; }
        public string? JobTitle2 { get; set; }
        public string? NatureOfBusiness { get; set; }
        public string? ExpLvlOfAc { get; set; }
        public string? RiskRating { get; set; }
        public string? CountryOfResidence { get; set; }
        public string? Pep { get; set; }
        public string? MaritalStatu { get; set; }
        public string? TransactionCount { get; set; }
        public string? WaiveTransFee { get; set; }
        public int CifId { get; set; }
    }
}
