using System;
using System.Collections.Generic;

namespace Standing_Order_Vat_App.DAL.GB_Register
{
    public partial class DataStage
    {
        public string? MajorTypeCode { get; set; }
        public string? AccountNumber { get; set; }
        public string? CifNumber { get; set; }
        public string? DeleteCod { get; set; }
        public string? Salutation { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? AddressNames { get; set; }
        public string? Address { get; set; }
        public string? AddressCont { get; set; }
        public string? City { get; set; }
        public string? Countr { get; set; }
        public string? ZipCode { get; set; }
        public string? SsnEin { get; set; }
        public string? OfficerInitials { get; set; }
        public string? MailCode { get; set; }
        public string? BranchNumber { get; set; }
        public string? DateOpened { get; set; }
        public string? FirstHistory { get; set; }
        public string? ClearFlag { get; set; }
        public string? AccountStatus { get; set; }
        public string? RestrictedAcc { get; set; }
        public string? IndirectRelCode { get; set; }
        public string? CombinedStmtCode { get; set; }
        public string? TaxId { get; set; }
        public string? MiscCode1 { get; set; }
        public string? EconomicCode { get; set; }
        public string? EccBs2Code { get; set; }
        public string? GLCode { get; set; }
        public string? DateLastChange { get; set; }
        public string? PhoneNumber { get; set; }
        public string? InterestWHCode { get; set; }
        public string? YtdInterestWH { get; set; }
        public string? YesterdayBalance { get; set; }
        public string? IntrstAccruedToday { get; set; }
        public string? IntrstAccruedMonth { get; set; }
        public string? InterestWHCert { get; set; }
        public string? YtdInterestA { get; set; }
        public string? DateLoaded { get; set; }
        public string? DateZeroed { get; set; }
        public string? _2ndUsageCode { get; set; }
        public string? ForeignCurrCode { get; set; }
        public string? MultipleSignatures { get; set; }
        public string? OfacReportingFlag { get; set; }
        public string? Birthdate { get; set; }
        public string? _2ndPhoneNumber { get; set; }
        public string? DateLastCustCont { get; set; }
        public string? ProductDefinition { get; set; }
        public string? ConsumerAcctFlag { get; set; }
        public string? ClassificationCode { get; set; }
        public string? CollateralType { get; set; }
        public string? RelatedPartyType { get; set; }
        public string? Unused { get; set; }
        public string? RestructuredLoans { get; set; }
        public string? Unused2 { get; set; }
        public string? DormantDate { get; set; }
        public string? InactiveDate { get; set; }
        public string? ClosingDate { get; set; }
        public string? CensusTract { get; set; }
        public string? HmdaStateCode { get; set; }
        public string? HmdaCountyCode { get; set; }
        public string? SicCode { get; set; }
        public string? AdditionalNames { get; set; }
        public string? AdditionalNames2 { get; set; }
        public string? UtilityPaymen { get; set; }
        public string? CardAccoun { get; set; }
        public string? AtmAchStatement { get; set; }
        public string? RiskRateCode { get; set; }
        public string? LimitedTransa { get; set; }
        public string? ReportCode { get; set; }
        public string? BalInBaseCurrency { get; set; }
        public string? AtmLocalWDLimit { get; set; }
        public string? PriorYearInt { get; set; }
        public string? ProductType { get; set; }
        public string? _66 { get; set; }
        public string? RegPOptOutFlag { get; set; }
        public string? ShortName { get; set; }
        public string? TickerMessage1 { get; set; }
        public string? TickerMessage2 { get; set; }
        public string? TickerMessage3 { get; set; }
        public string? MsaCode { get; set; }
        public string? _2ndNameDob { get; set; }
        public string? _3rdNameDob { get; set; }
        public string? _4thNameDob { get; set; }
        public string? EmployeeOperator { get; set; }
        public string? _3rdPhone { get; set; }
        public string? _4thPhone { get; set; }
        public string? ChildSupportColl { get; set; }
        public string? FdicInsuranceCat { get; set; }
        public string? RiskRating { get; set; }
        public string? ReservedForFuture { get; set; }
        public string? ExcludeCifValue { get; set; }
        public string? _2ndNamePhone { get; set; }
        public string? SynergySubType { get; set; }
        public string? SynergyExceptions { get; set; }
        public string? SynergyTrackingId { get; set; }
        public string? PhoneExtension { get; set; }
        public string? BegDayAccr { get; set; }
        public string? NtellerLoginsCtd { get; set; }
        public string? NtellerLoginsYtd { get; set; }
        public string? _2ndTaxId { get; set; }
        public string? _2ndSsnEin { get; set; }
        public string? _2ndSalutation { get; set; }
        public string? _2ndFirstName { get; set; }
        public string? _2ndLastName { get; set; }
        public string? _2ndAddress { get; set; }
        public string? _2ndCity { get; set; }
        public string? _2ndState { get; set; }
        public string? _2ndZipCode { get; set; }
        public string? _3rdSalutation { get; set; }
        public string? _3rdFirstName { get; set; }
        public string? _3rdLastName { get; set; }
        public string? _4thSalutation { get; set; }
        public string? _4thFirstName { get; set; }
        public string? _4thLastName { get; set; }
        public string? StartDtToUseAddr { get; set; }
        public string? EndDateToUseAddr { get; set; }
        public string? UpdateAddrDates { get; set; }
        public string? _3rdTaxIdCode { get; set; }
        public string? _3rdSsnEin { get; set; }
        public string? _4thTaxIdCode { get; set; }
        public string? _4thSsnEin { get; set; }
        public string? AdditionalAddress { get; set; }
        public string? _2ndNameOwnership { get; set; }
        public string? _3rdNameOwnership { get; set; }
        public string? _4thNameOwnership { get; set; }
        public string? EsiStatements { get; set; }
        public string? IrsCorrection { get; set; }
        public string? DateOfDeath { get; set; }
        public string? IrsNotice { get; set; }
        public string? _1042SRequired { get; set; }
        public string? NewEccbBs1Code { get; set; }
        public string? NewEccbBs2Code { get; set; }
        public string? PrintStateme { get; set; }
        public string? NewBs1Code { get; set; }
        public string? NewBs2Code { get; set; }
        public string? AccountData { get; set; }
    }
}
