using System;
using System.Collections.Generic;

namespace Standing_Order_Vat_App.DAL.GB_Register
{
    public partial class Ddum
    {
        public string? AccountNumber { get; set; }
        public string? CurrentBalance { get; set; }
        public string? MemoBalance { get; set; }
        public string? CtdAverageBalanceYtd { get; set; }
        public string? CtdLowestBalance { get; set; }
        public string? LastStmtBalance { get; set; }
        public string? DateLastCheque { get; set; }
        public string? DateLastDeposit { get; set; }
        public string? DateLastCycled { get; set; }
        public string? TypeCode { get; set; }
        public string? RateCode { get; set; }
        public string? CtdDebits { get; set; }
        public string? CtdCredits { get; set; }
        public string? InterestRate { get; set; }
        public string? ServiceChargeCode { get; set; }
        public string? YtdODDays { get; set; }
        public string? ODDaysLastYear { get; set; }
        public string? ConsecutiveDaysOd { get; set; }
        public string? DateLastOverdraft { get; set; }
        public string? _1DayFloatA { get; set; }
        public string? _2DayFloatA { get; set; }
        public string? _3DayFloatA { get; set; }
        public string? AggregateFloatAmt { get; set; }
        public string? CardholderNumber { get; set; }
        public string? StatementRequest { get; set; }
        public string? StmtCycleCode { get; set; }
        public string? CtdChecks { get; set; }
        public string? LastChequeA { get; set; }
        public string? LastDeposit { get; set; }
        public string? DatePreviousStmt { get; set; }
        public string? PreviousStmtBal { get; set; }
        public string? InterestEarned { get; set; }
        public string? YtdInterest { get; set; }
        public string? YtdAverageBalanceYtd { get; set; }
        public string? YtdServiceC { get; set; }
        public string? OdType { get; set; }
        public string? ODLimitWhole { get; set; }
        public string? OverdraftRate { get; set; }
        public string? ODInterestCode { get; set; }
        public string? DdaMiscFld1 { get; set; }
        public string? DdaMiscFld2 { get; set; }
        public string? DateODExpires { get; set; }
        public string? ODInterest { get; set; }
        public string? ODIntrstPa { get; set; }
        public string? ExemptOdNsfChrg { get; set; }
        public string? StatementSortCode { get; set; }
        public string? FixedMoneyMktRate { get; set; }
        public string? ODPenaltyRate { get; set; }
        public string? UnpostToday { get; set; }
        public string? CtdAtmWithdrawals { get; set; }
        public string? TransitDic { get; set; }
        public string? ClearingDic { get; set; }
        public string? LowCollectedBal { get; set; }
        public string? AggregateCre { get; set; }
        public string? CtdDaysOverdrawn { get; set; }
        public string? AggregateOdBalance { get; set; }
        public string? StmtMessageCode { get; set; }
        public string? YtdNsfChecks { get; set; }
        public string? YtdDebits { get; set; }
        public string? YtdCredits { get; set; }
        public string? PreviousYearDebits { get; set; }
        public string? PrevYearCredits { get; set; }
        public string? PrevYearNsfChks { get; set; }
        public string? PrevYrAverageBal { get; set; }
        public string? LowBalanceMtd { get; set; }
        public string? OnUsDic { get; set; }
        public string? DiscountOnSerChg { get; set; }
        public string? SerChgRunningBal { get; set; }
        public string? FixedSerChgAmount { get; set; }
        public string? MaximumServCharge { get; set; }
        public string? CdXYSCCyclTd { get; set; }
        public string? CalcSerChargeCtd { get; set; }
        public string? TargetBalance { get; set; }
        public string? CounterChecksCtd { get; set; }
        public string? HighBalanceAmount { get; set; }
        public string? TransferToType { get; set; }
        public string? TransferToAccount { get; set; }
        public string? LowBalanceAmount { get; set; }
        public string? TransferFromType { get; set; }
        public string? AcctToTrnsfrFrom { get; set; }
        public string? AcctForInterest { get; set; }
        public string? AcctTypeForIntr { get; set; }
        public string? TransferOutAmount { get; set; }
        public string? TrnsfrSCIn { get; set; }
        public string? TrnsfrSCOut { get; set; }
        public string? BankClubCode { get; set; }
        public string? BankClubChgAmt { get; set; }
        public string? FieldNotUsed { get; set; }
        public string? YtdTransitItmCnt { get; set; }
        public string? YtdClringItemCnt { get; set; }
        public string? _45DayFloat { get; set; }
        public string? _610DayFloa { get; set; }
        public string? _1115DayFlo { get; set; }
        public string? Over15DayF { get; set; }
        public string? ODOrNsfCurMo { get; set; }
        public string? ODOrNsfPrevMo { get; set; }
        public string? ODOrNsfPrevMo2 { get; set; }
        public string? ODOrNsfPrevMo3 { get; set; }
        public string? ODOrNsfPrevMo4 { get; set; }
        public string? ODOrNsfPrevMo5 { get; set; }
        public string? ODOrNsfPrevMo6 { get; set; }
        public string? DtLstODNsf5000 { get; set; }
        public string? MtdCredCnt { get; set; }
        public string? ClubChargeCode { get; set; }
        public string? CheckSizeCode { get; set; }
        public string? MtdHiBal { get; set; }
        public string? MultiStmtGrenada { get; set; }
        public string? YtdHiBal { get; set; }
        public string? MtdCreditTo { get; set; }
        public string? MtdAggrBala { get; set; }
        public string? DailyODAccrual { get; set; }
        public string? ComtelBalance { get; set; }
        public string? AggrDebits { get; set; }
        public string? ChargedOff { get; set; }
        public string? AutoClose { get; set; }
        public string? AmtChargedOff { get; set; }
        public string? MiscField2 { get; set; }
        public string? MiscField3 { get; set; }
        public string? ExemptChgBack { get; set; }
        public string? CheckTruncation { get; set; }
        public string? OpenDepAmt { get; set; }
        public string? MtdAggBal { get; set; }
        public string? PrevCycleCode { get; set; }
        public string? PrevSerChgCode { get; set; }
        public string? CtdSerChgDebits { get; set; }
        public string? CtdSerChgCredits { get; set; }
        public string? PersMmdaTrans { get; set; }
        public string? TotTransferDebits { get; set; }
        public string? TotInclearings { get; set; }
        public string? CurrentViolation { get; set; }
        public string? ViolationHistory { get; set; }
        public string? SpecPostageSC { get; set; }
        public string? ForeignAtmWDs { get; set; }
        public string? ExemptForAtmSC { get; set; }
        public string? IntrEarndNo { get; set; }
        public string? PrevExcessViol { get; set; }
        public string? DownloadAcct { get; set; }
        public string? ExemptFromPosChg { get; set; }
        public string? DsiImageHorizontal { get; set; }
        public string? DsiImageVertical { get; set; }
        public string? DsiImagePgFormat { get; set; }
        public string? DsiImageFrontBck { get; set; }
        public string? DsiImageDrCr { get; set; }
        public string? QtdHighBalance { get; set; }
        public string? QtdHighODBal { get; set; }
        public string? QtdIntrstExp { get; set; }
        public string? QtdIntrstInc { get; set; }
        public string? LoanLossProv { get; set; }
        public string? SpecificProv { get; set; }
        public string? SecurityValue { get; set; }
        public string? SecurityCodes { get; set; }
        public string? PosTransCtd { get; set; }
        public string? CtdAverageBalance { get; set; }
        public string? CtdAverageF { get; set; }
        public string? YtdAverageBalance { get; set; }
        public string? YtdAverageC { get; set; }
        public string? AvailableBalance { get; set; }
        public string? AvailCrSafetyChk { get; set; }
        public string? NsfItemFee { get; set; }
        public string? DateChargedOff { get; set; }
        public string? ChargeOffRecovery { get; set; }
        public string? DateOfRecovery { get; set; }
        public string? YtdNsfPresented { get; set; }
        public string? PrevYearNsfItems { get; set; }
        public string? YtdNsfReturns { get; set; }
        public string? PrevYrNsfReturns { get; set; }
        public string? ODIntRateCode { get; set; }
        public string? ODIntRateAdj { get; set; }
        public string? YtdODIntE { get; set; }
        public string? TotalAtmWDMtd { get; set; }
        public string? ForeignAtmWDMtd { get; set; }
        public string? TotalAtmWDYtd { get; set; }
        public string? ForeignAtmWDYtd { get; set; }
        public string? TotalAtmWDPrYr { get; set; }
        public string? ForiegnAtmWDPrY { get; set; }
        public string? PosTransactionsMtd { get; set; }
        public string? PosAmountMt { get; set; }
        public string? PosTransactionsYtd { get; set; }
        public string? AmountOfPos { get; set; }
        public string? NumberOfPosPrYr { get; set; }
        public string? PosAmountLa { get; set; }
        public string? AnalysisCounter1 { get; set; }
        public string? AnalysisCounter2 { get; set; }
        public string? AnalysisCounter3 { get; set; }
        public string? AnalysisCounter4 { get; set; }
        public string? AnalysisCounter5 { get; set; }
        public string? AnalysisCounter6 { get; set; }
        public string? AnalysisCounter7 { get; set; }
        public string? AnalysisCounter8 { get; set; }
        public string? AnalysisCounter9 { get; set; }
        public string? AnalysisCounter10 { get; set; }
        public string? AnalysisAmounT1 { get; set; }
        public string? AnalysisAmounT2 { get; set; }
        public string? AnalysisAmounT3 { get; set; }
        public string? AnalysisAmounT4 { get; set; }
        public string? AnalysisAmounT5 { get; set; }
        public string? AnalysisAmounT6 { get; set; }
        public string? AnalysisAmounT7 { get; set; }
        public string? AnalysisAmounT8 { get; set; }
        public string? AnalysisAmounT9 { get; set; }
        public string? AnalysisAmounT10 { get; set; }
        public string? StopPyNoticeFlag { get; set; }
        public string? StopPyAutoChgFlg { get; set; }
        public string? UncollectedBalance { get; set; }
        public string? PriorDayUncollBal { get; set; }
        public string? AtmCreditsCtd { get; set; }
        public string? ForeignAtmCrCtd { get; set; }
        public string? TotalAtmCreditMtd { get; set; }
        public string? ForeignAtmCrMtd { get; set; }
        public string? TotlAtmCreditsYtd { get; set; }
        public string? ForeignAtmCrYtd { get; set; }
        public string? AtmCreditsPriorYr { get; set; }
        public string? ForeignAtmCrPrYr { get; set; }
        public string? AnalysisPrimAcct { get; set; }
        public string? _2ndTransferToType { get; set; }
        public string? _2ndTransferToAcct { get; set; }
        public string? _2ndTrfFromType { get; set; }
        public string? _2ndTrfFromAcct { get; set; }
        public string? CashMgmtRepoFlag { get; set; }
        public string? CshMgtCollBalFlg { get; set; }
        public string? OdLoanPymtFlag { get; set; }
        public string? InterestDispCode { get; set; }
        public string? AchRoutingNumber { get; set; }
        public string? AchTransactionCode { get; set; }
        public string? AchAccountNumber { get; set; }
        public string? StmtSrtPrAcctFlg { get; set; }
        public string? JanAvgBal { get; set; }
        public string? FebAvgBal { get; set; }
        public string? MarAvgBal { get; set; }
        public string? AprAvgBal { get; set; }
        public string? MayAvgBal { get; set; }
        public string? JunAvgBal { get; set; }
        public string? JulAvgBal { get; set; }
        public string? AugAvgBal { get; set; }
        public string? SepAvgBal { get; set; }
        public string? OctAvgBal { get; set; }
        public string? NovAvgBal { get; set; }
        public string? DecAvgBal { get; set; }
        public string? ServiceChgWaiveCd { get; set; }
        public string? SerChrgWaiveDate { get; set; }
        public string? SerChgsWaivedYtd { get; set; }
        public string? SerChgsWaivedLYr { get; set; }
        public string? SChgsReversedYtd { get; set; }
        public string? SChgsReversedPyr { get; set; }
        public string? NsfWaivedYtdAcct { get; set; }
        public string? NsfWaivedPyrAcct { get; set; }
        public string? NsfWaivedOperYtd { get; set; }
        public string? NsfWaivedOperPyr { get; set; }
        public string? NsfReversedYtd { get; set; }
        public string? NsfReversedPyr { get; set; }
        public string? AcctAnalysisType { get; set; }
        public string? AnalysisSettlmtMo { get; set; }
        public string? AnalysisSettleFrq { get; set; }
        public string? PrvMonthCar { get; set; }
        public string? CurMonthCar { get; set; }
        public string? ExemptSalesTax { get; set; }
        public string? OdChargesYtd { get; set; }
        public string? OdChargeLastYear { get; set; }
        public string? OdChgRefundedYtd { get; set; }
        public string? OdChrgRefundLYr { get; set; }
        public string? TotalHoldAm { get; set; }
        public string? DatalinkMtdVceInq { get; set; }
        public string? DatalinkYtdVceInq { get; set; }
        public string? CollectedBalance { get; set; }
        public string? BillPayEnrollDate { get; set; }
        public string? BillPaySCCode { get; set; }
        public string? PpEnrollmentFee { get; set; }
        public string? BillPaySCCycles { get; set; }
        public string? BillPayTransCtd { get; set; }
        public string? BillPayTotalTrans { get; set; }
        public string? MultipleStatements { get; set; }
        public string? DateLstStmPrinted { get; set; }
        public string? ReClassFlag { get; set; }
        public string? ReclasThrshl { get; set; }
        public string? ReClassAmount { get; set; }
        public string? ReClassCounter { get; set; }
        public string? ReClassCntrOvrd { get; set; }
        public string? ResFundsAcctType { get; set; }
        public string? ResFundsSwpTime { get; set; }
        public string? FraudAlertFlag { get; set; }
        public string? ExcludeCredBureau { get; set; }
        public string? CashMgmtOverdraw { get; set; }
        public string? RegDdOdDisclosure { get; set; }
        public string? ODChgsThisCycle { get; set; }
        public string? RetChgsThisCycle { get; set; }
        public string? ODChargesYtd1 { get; set; }
        public string? ReturnItemChgs { get; set; }
        public string? _12MnthAverageBal { get; set; }
        public string? YtdBounceCharges { get; set; }
        public string? BounceChgPriorYr { get; set; }
        public string? PriorYrRegDdOD { get; set; }
        public string? PriorYrRetItmChg { get; set; }
        public string? IncludeAchIndId { get; set; }
        public string? AchPositivePay { get; set; }
        public string? ExpandedSCCode { get; set; }
        public string? CshMgmtFloatSweep { get; set; }
        public string? ReserveFundBalance { get; set; }
        public string? ReserveFundsAip { get; set; }
        public string? CtdAchCredits { get; set; }
        public string? CtdAchDebits { get; set; }
        public string? CtdPosSignature { get; set; }
        public string? CtdPosPinBased { get; set; }
        public string? InterestRateAdj { get; set; }
        public string? DailyWireLi { get; set; }
        public string? ReserveFundProduct { get; set; }
        public string? CshMgmtProcessLvl { get; set; }
        public string? WaiveOutgWireFee { get; set; }
        public string? UseAchFilters { get; set; }
        public string? BncPortionPdItems { get; set; }
        public string? BncPortionTrnFees { get; set; }
        public string? BncPortionSC { get; set; }
        public string? BncPortionDlyFee { get; set; }
        public string? BncNsfItemsLife { get; set; }
        public string? BncDaysODLife { get; set; }
        public string? BncNsfItmsQtd { get; set; }
        public string? BncDaysODQtd { get; set; }
        public string? BncTimesODQtd { get; set; }
        public string? BncAmountNsfQtd { get; set; }
        public string? BncNsfItmsLstQtr { get; set; }
        public string? BncDaysODLstQtr { get; set; }
        public string? BncTimeODLstQtr { get; set; }
        public string? BncAmtNsfLastQtr { get; set; }
        public string? BncPlanCode { get; set; }
        public string? BncStatusCode { get; set; }
        public string? BncLockedLimit { get; set; }
        public string? BncShowInNsfprc { get; set; }
        public string? BncMailLetters { get; set; }
        public string? BncMailNotices { get; set; }
        public string? BncLetter1Sent { get; set; }
        public string? BncLetter2Sent { get; set; }
        public string? BncLetter3Sent { get; set; }
        public string? BncLetter4Sent { get; set; }
        public string? BncLetter5Sent { get; set; }
        public string? BncLetter6Sent { get; set; }
        public string? BncLetter7Sent { get; set; }
        public string? BncLetter8Sent { get; set; }
        public string? BncLetter9Sent { get; set; }
        public string? BncForceLetter { get; set; }
        public string? BncLtrPrintToday { get; set; }
        public string? BncExcUseLtrs { get; set; }
        public string? BncDtLstExcLtr { get; set; }
        public string? BncDateActivated { get; set; }
        public string? BncPostStatusCode { get; set; }
        public string? BncTimesInFs { get; set; }
        public string? BncFsAccountNbr { get; set; }
        public string? BncFsAcctBalance { get; set; }
        public string? RewardsPlanCode { get; set; }
        public string? RewardCriteriaMet { get; set; }
        public string? BncExcUseLtrPrt { get; set; }
        public string? Metro2EcoaCode { get; set; }
        public string? Metro2AddrIndic { get; set; }
        public string? Metro2CondCode { get; set; }
        public string? TransferInAmount { get; set; }
        public string? ExemptAutoChgOff { get; set; }
        public string? BeginningBalToday { get; set; }
        public string? ExcludeFromPayall { get; set; }
        public string? CtdElectrncDebits { get; set; }
        public string? CtdElectrncCredits { get; set; }
        public string? RegEOptIn { get; set; }
        public string? RegEOdBalance { get; set; }
        public string? RegEAggOdBal { get; set; }
        public string? RegEOdDays { get; set; }
        public string? RegEOptInDate { get; set; }
        public string? RegEDateRevoked { get; set; }
        public string? RegEConfirmDate { get; set; }
        public string? RegEPrintFlag { get; set; }
        public string? SuppressNsfNotice { get; set; }
        public string? WaiveIncWireFee { get; set; }
        public string? YtdOdFeeWvdBal { get; set; }
        public string? PrYtdOdFeeWvBal { get; set; }
        public string? YtdOdFeeWvItmLmt { get; set; }
        public string? PrYtdOdWvItmLmt { get; set; }
        public string? StatementFormat { get; set; }
        public string? CheckNumberGap { get; set; }
        public string? OdpOccasionCurrent { get; set; }
        public string? OdpOccasn1MoAgo { get; set; }
        public string? OdpOccasn2MoAgo { get; set; }
        public string? OdpOccasn3MoAgo { get; set; }
        public string? OdpOccasn4MoAgo { get; set; }
        public string? OdpOccasn5MoAgo { get; set; }
        public string? OdpOccasn6MoAgo { get; set; }
        public string? OdpOccasn7MoAgo { get; set; }
        public string? OdpOccasn8MoAgo { get; set; }
        public string? OdpOccasn9MoAgo { get; set; }
        public string? OdpOccasn10MoAgo { get; set; }
        public string? OdpOccasn11MoAgo { get; set; }
        public string? OdpOccasn12MoAgo { get; set; }
        public string? OdpOccasPrv12Mo { get; set; }
        public string? OdpOccasCurPrv11 { get; set; }
        public string? OdpOccasLifetime { get; set; }
        public string? OdpContactType { get; set; }
        public string? OdpLastContactDt { get; set; }
        public string? OdpContactFlag { get; set; }
        public string? OdpCounterResets { get; set; }
        public string? OdpDtCntctFlagged { get; set; }
        public string? OdpDateLastReset { get; set; }
        public string? OdpNotifyFlag { get; set; }
        public string? AccountBypassEip { get; set; }
        public string? RegEItemsWvdMtd { get; set; }
        public string? RegEItemsWvdLmth { get; set; }
        public string? RegEItemsWvdYtd { get; set; }
        public string? RegEItemsWvdLyr { get; set; }
        public string? YtdOdFeesWvdTier { get; set; }
        public string? PrYrOdFeeWvTier { get; set; }
        public string? DaysPastMaturity { get; set; }
        public string? NonPerformingDda { get; set; }
        public string? NonPerformingDate { get; set; }
        public string? AccrIntAtNonPerf { get; set; }
        public string? AutoNonPerforming { get; set; }
        public string? WaiveAtmUsageCr { get; set; }
        public string? AtmUsageCreditCtd { get; set; }
        public string? SecByResCommMtg { get; set; }
        public string? CashSecurity { get; set; }
        public string? DateLstEvaluation { get; set; }
        public string? ValuationReportPrep { get; set; }
        public int DdaId { get; set; }
    }
}
