using System;
using System.Collections.Generic;

namespace Standing_Order_Vat_App.DAL.GB_Register
{
    public partial class Loan
    {
        public string? AccountNumber { get; set; }
        public string? TypeCode { get; set; }
        public string? ClassCode { get; set; }
        public string? InterestEarn { get; set; }
        public string? NextPaymentDate { get; set; }
        public string? MaturityDate { get; set; }
        public string? CorrespondingAcct { get; set; }
        public string? InterestColl { get; set; }
        public string? DbCrLifeEarned { get; set; }
        public string? DbCLColl { get; set; }
        public string? AHEarned { get; set; }
        public string? AHCollected { get; set; }
        public string? RegularPayme { get; set; }
        public string? PartialPayme { get; set; }
        public string? DateLastPayment { get; set; }
        public string? PaymentFrequency { get; set; }
        public string? AmountLastP { get; set; }
        public string? Delinquent30Days { get; set; }
        public string? Delinquent60Days { get; set; }
        public string? Delinquent90Days { get; set; }
        public string? OfExtensions { get; set; }
        public string? InterestRate { get; set; }
        public string? PastDueChgsEarnd { get; set; }
        public string? PDChgsCollected { get; set; }
        public string? YtdLateChgsPaid { get; set; }
        public string? LoanFeeColl { get; set; }
        public string? OriginalLoanAmt { get; set; }
        public string? Term { get; set; }
        public string? InterestPaidTotal { get; set; }
        public string? IntPaidPast { get; set; }
        public string? ParticipationCode { get; set; }
        public string? DateInterestNext { get; set; }
        public string? DealerNumber { get; set; }
        public string? DateFinancialStmt { get; set; }
        public string? Ucc1ExpirationDte { get; set; }
        public string? DateInsurExpires { get; set; }
        public string? Collateral { get; set; }
        public string? SpecialInstruction { get; set; }
        public string? CurrentBalance { get; set; }
        public string? DaysLate { get; set; }
        public string? DaysBase { get; set; }
        public string? NoticeNumber { get; set; }
        public string? DelinquentFlag { get; set; }
        public string? LateCounter { get; set; }
        public string? BomLiability { get; set; }
        public string? TypeCreditLife { get; set; }
        public string? DateIntPaidTo { get; set; }
        public string? DealerEarned { get; set; }
        public string? DealerCollected { get; set; }
        public string? OriginationFee { get; set; }
        public string? InterestFreqCode { get; set; }
        public string? LateChargeDay { get; set; }
        public string? PaymentsReceived { get; set; }
        public string? VariableRateCode { get; set; }
        public string? RateAdjustment { get; set; }
        public string? VariableRateFreq { get; set; }
        public string? NextRepricingDate { get; set; }
        public string? DefaultRate { get; set; }
        public string? PartMasterLoan { get; set; }
        public string? NonAccrualChargoff { get; set; }
        public string? PayrollPayme { get; set; }
        public string? MiscUser2 { get; set; }
        public string? OriginalIntRate { get; set; }
        public string? BoyInterestRate { get; set; }
        public string? MaxYearlyIncrease { get; set; }
        public string? MaxYearlyDecrease { get; set; }
        public string? MaxLifeIncrease { get; set; }
        public string? MaxLifeDecrease { get; set; }
        public string? RatingCode { get; set; }
        public string? LevelCrLifeEarnd { get; set; }
        public string? LevelCrLifeColl { get; set; }
        public string? CrLifeExpireDate { get; set; }
        public string? IntRebateCa { get; set; }
        public string? RenewalCode { get; set; }
        public string? WhoseAccount { get; set; }
        public string? MaximumLateCharge { get; set; }
        public string? CureNoticeFlag { get; set; }
        public string? _1098Required { get; set; }
        public string? CurePrintFlag { get; set; }
        public string? DateLstHomeEqSt { get; set; }
        public string? FixPaymentA { get; set; }
        public string? CorresAccountMod { get; set; }
        public string? PaymtOnDelinquent { get; set; }
        public string? DateLastExtension { get; set; }
        public string? EscrowBalance { get; set; }
        public string? YtdIntCollOnExt { get; set; }
        public string? QtdAggregateBal { get; set; }
        public string? StudentLoanReport { get; set; }
        public string? CollateralFile { get; set; }
        public string? ModificationDate { get; set; }
        public string? CrBurPayoffCode { get; set; }
        public string? CreditLimit { get; set; }
        public string? LineCommitment { get; set; }
        public string? DateNonAccrual { get; set; }
        public string? NonAccrualEa { get; set; }
        public string? NonAccrualPa { get; set; }
        public string? DateChargedOff { get; set; }
        public string? ChargeOffBalance { get; set; }
        public string? PymtNoticeFlag { get; set; }
        public string? PymntDayOfMonth { get; set; }
        public string? Class5IntrDay { get; set; }
        public string? TitleDateDue { get; set; }
        public string? TitleInspectionDt { get; set; }
        public string? MiscEscrowDate { get; set; }
        public string? DateDeedTrustDue { get; set; }
        public string? CouponTapeFlag { get; set; }
        public string? AmtMemoPostedTody { get; set; }
        public string? Fasb91OrigCost { get; set; }
        public string? Fasb91OrigFeeColl { get; set; }
        public string? Fasb91OrigCostErn { get; set; }
        public string? Fasb91OrigFeeErn { get; set; }
        public string? Fasb91CostAccTod { get; set; }
        public string? Fasb91FeeAccTod { get; set; }
        public string? Fasb91CostAccYtd { get; set; }
        public string? Fasb91FeeAccYtd { get; set; }
        public string? CurrentBaseRate { get; set; }
        public string? PreviousBaseRate1 { get; set; }
        public string? YtdAggBalOnly { get; set; }
        public string? PreviousIntRate { get; set; }
        public string? NewPaymentA { get; set; }
        public string? NewPaymentE { get; set; }
        public string? CouponsPrinted { get; set; }
        public string? CouponsPerOrder { get; set; }
        public string? CouponsRemaining { get; set; }
        public string? YtdInterest { get; set; }
        public string? StudentFeeCode { get; set; }
        public string? StudentBillCode { get; set; }
        public string? StudentAllowCode { get; set; }
        public string? StudentTypeCode { get; set; }
        public string? PointsCollec { get; set; }
        public string? PointsReportable { get; set; }
        public string? Amortized { get; set; }
        public string? InitialLoanOfficer { get; set; }
        public string? EscrowFlag { get; set; }
        public string? LeaseType { get; set; }
        public string? LeaseStateCode { get; set; }
        public string? LeaseSalesTxRate { get; set; }
        public string? TrwLoanType { get; set; }
        public string? TrwStatusCode { get; set; }
        public string? LateChargeNumber { get; set; }
        public string? AdvDatesForRate { get; set; }
        public string? MiscLoanField { get; set; }
        public string? Fas91CalcFlag { get; set; }
        public string? Fas91CostEarned { get; set; }
        public string? Fas91FeesEarned { get; set; }
        public string? PaymentScheduleFlg { get; set; }
        public string? TypeAH { get; set; }
        public string? BalLastLoanStmt { get; set; }
        public string? SimpleIntDealRte { get; set; }
        public string? SimpIntDealType { get; set; }
        public string? OriginalCommitAmt { get; set; }
        public string? IntPaidByO { get; set; }
        public string? PriorYearsI { get; set; }
        public string? RiskBasedCap { get; set; }
        public string? GuaranteedPort { get; set; }
        public string? RskBsCapGuar { get; set; }
        public string? AmtPrincLst { get; set; }
        public string? AmtIntLast { get; set; }
        public string? PrincBilled { get; set; }
        public string? IntBilledNo { get; set; }
        public string? DateLoanLstRenew { get; set; }
        public string? BalLoanLastRenew { get; set; }
        public string? ReportToCrBureau { get; set; }
        public string? PartialChgOffBal { get; set; }
        public string? PartChgOffIenc { get; set; }
        public string? ParChgOffIntTdy { get; set; }
        public string? ParChgOffI { get; set; }
        public string? AmortSchedLoanBal { get; set; }
        public string? CumulDaysDelinq { get; set; }
        public string? SecondMktLoanTyp { get; set; }
        public string? NumberOfRenewals { get; set; }
        public string? MortInterestRefund { get; set; }
        public string? MatDateAtRenewal { get; set; }
        public string? NonAccrualI { get; set; }
        public string? QtdHighBalance { get; set; }
        public string? QtdInterest { get; set; }
        public string? LoanLossProv { get; set; }
        public string? SpecificProv { get; set; }
        public string? SecurityValue { get; set; }
        public string? SecurityCodes { get; set; }
        public string? CrBureauBadHst { get; set; }
        public string? CreditBrPstMoDl { get; set; }
        public string? PrntPayDueNotice { get; set; }
        public string? BcalcMaturityDate { get; set; }
        public string? OfBalForPymt { get; set; }
        public string? PaymentToCalcAmt { get; set; }
        public string? IntRoundingFlag { get; set; }
        public string? TodaySPayoff { get; set; }
        public string? UnusedCreditCommit { get; set; }
        public string? InterestAdju { get; set; }
        public string? PrincipalDue { get; set; }
        public string? BalDueAftrPaymnt { get; set; }
        public string? DecBalCrLifeDue { get; set; }
        public string? LevelCrLifeDue { get; set; }
        public string? AHAdjustment { get; set; }
        public string? TotalInsuranceAdj { get; set; }
        public string? DealerDiscountAdj { get; set; }
        public string? LateChargeAdj { get; set; }
        public string? ScheduledRate { get; set; }
        public string? DailyIntFactor { get; set; }
        public string? AmountPastD { get; set; }
        public string? SplitParticPymnt { get; set; }
        public string? LeaseUnguarResid { get; set; }
        public string? LeaseSecurityDep { get; set; }
        public string? LeasePurchOption { get; set; }
        public string? LeaseGuarResid { get; set; }
        public string? LeasePersnlPtyTx { get; set; }
        public string? FredMacFanMae { get; set; }
        public string? EscrowIntPaidYtd { get; set; }
        public string? EscrowIntPdLstYr { get; set; }
        public string? InterestPaid { get; set; }
        public string? EscrowPaymentAmt { get; set; }
        public string? DateDelinq30Days { get; set; }
        public string? RevolvCreditPlan { get; set; }
        public string? TtlInsBilld { get; set; }
        public string? TtlAnnFeesNotPd { get; set; }
        public string? BillingTypeCode { get; set; }
        public string? AdvanceBillingDays { get; set; }
        public string? InterestApplyCode { get; set; }
        public string? StopPayNoticeFlag { get; set; }
        public string? StopPayChargeFlag { get; set; }
        public string? PmtSplitPriorFlg { get; set; }
        public string? UnappliedPay { get; set; }
        public string? PaymentApplyCode { get; set; }
        public string? EscrowPastDue { get; set; }
        public string? PaymentSourceCode { get; set; }
        public string? AchRoutingNumber { get; set; }
        public string? AchTransactionCode { get; set; }
        public string? AchAccountNumber { get; set; }
        public string? InsuranceSta { get; set; }
        public string? InsuranceTerm { get; set; }
        public string? MaxRtIncEachOcc { get; set; }
        public string? MaxRtDecEachOcc { get; set; }
        public string? RlvCrIntLstStmt { get; set; }
        public string? BalAfterLstAdv { get; set; }
        public string? MinRateChgAllowd { get; set; }
        public string? CollectionSrvcDay { get; set; }
        public string? PayScheduleType { get; set; }
        public string? BeginBalToday { get; set; }
        public string? PIPayment { get; set; }
        public string? FasbMaturityDate { get; set; }
        public string? CollectorInitials { get; set; }
        public string? MajorLineNumber { get; set; }
        public string? DemandLoan { get; set; }
        public string? RepossessionStatus { get; set; }
        public string? CdForVarRateLn { get; set; }
        public string? DealerFloorPlan { get; set; }
        public string? AggAccrualBalance { get; set; }
        public string? TotIntrPdL { get; set; }
        public string? DaysToCure { get; set; }
        public string? DefaultRateFlag { get; set; }
        public string? DefaultRateDate { get; set; }
        public string? LateChrgePending { get; set; }
        public string? AutopayMemoPosted { get; set; }
        public string? PaymentRating { get; set; }
        public string? ComplianceCode { get; set; }
        public string? ConsumerInfo { get; set; }
        public string? CrBureauDelHist2 { get; set; }
        public string? MobPremiumAmount { get; set; }
        public string? MobPremiumPdTotal { get; set; }
        public string? MobPremLastBilled { get; set; }
        public string? MobPremiumUnpaid { get; set; }
        public string? DaysSinceMatDate { get; set; }
        public string? AgencyCode { get; set; }
        public string? PayoffReported { get; set; }
        public string? FundingDate { get; set; }
        public string? MobClTotalEarned { get; set; }
        public string? MobClTotalPaid { get; set; }
        public string? MobClEarnedToday { get; set; }
        public string? MobClEarnedMtd { get; set; }
        public string? MobClPaidMtd { get; set; }
        public string? MobClBillUnpaid { get; set; }
        public string? MobClLastBilled { get; set; }
        public string? MobClPlanCode { get; set; }
        public string? MobClMonthFactor { get; set; }
        public string? MobClStartDate { get; set; }
        public string? MobClEndDate { get; set; }
        public string? MobAhTotalEarned { get; set; }
        public string? MobAhTotalPaid { get; set; }
        public string? MobAhEarnedToday { get; set; }
        public string? MobAhEarnedMtd { get; set; }
        public string? MobAhPaidMtd { get; set; }
        public string? MobAhBillUnpaid { get; set; }
        public string? MobAhLastBilled { get; set; }
        public string? MobAhPlanCode { get; set; }
        public string? MobAhMonthFactor { get; set; }
        public string? MobAhStartDate { get; set; }
        public string? MobAhEndDate { get; set; }
        public string? InterestBeginDate { get; set; }
        public string? OnLineDelqPymnt { get; set; }
        public string? FraudAlertFlag { get; set; }
        public string? NextBaseRate { get; set; }
        public string? PayoffAtMaturity { get; set; }
        public string? LoanToValueRatio { get; set; }
        public string? PrePayPerCentage { get; set; }
        public string? PrepaymentPenalty { get; set; }
        public string? PreviousBaseRate { get; set; }
        public string? PendingAchTran { get; set; }
        public string? ReservedForFuture { get; set; }
        public string? SbaLoanStatus { get; set; }
        public string? SbaBasisPoints { get; set; }
        public string? CBDaysPastDue { get; set; }
        public string? AutoPayGraceDays { get; set; }
        public string? LonfrmReportMthd { get; set; }
        public string? AutomaticPmtDate { get; set; }
        public string? AutoPmtFrequency { get; set; }
        public string? AutoPayment { get; set; }
        public string? LoanFee1 { get; set; }
        public string? LoanFee2 { get; set; }
        public string? LoanFee3 { get; set; }
        public string? LoanFee4 { get; set; }
        public string? LoanFee5 { get; set; }
        public string? LoanFeesCol { get; set; }
        public string? LoanFeesEarned { get; set; }
        public string? LoanFeesErndToday { get; set; }
        public string? LoanFeesAtOrig { get; set; }
        public string? LoanFeesAddToBal { get; set; }
        public string? LoanFeesAtPayoff { get; set; }
        public string? LoanFeesBilled { get; set; }
        public string? FeesBilledN { get; set; }
        public string? SbaLatePmtDate { get; set; }
        public string? LoanAvailableBal { get; set; }
        public string? ChargeOffReason { get; set; }
        public string? MortgageIns { get; set; }
        public string? RightToCureDate { get; set; }
        public string? RightToCureReset { get; set; }
        public string? BeginningYearBal { get; set; }
        public string? TotalAmountDue { get; set; }
        public string? FreshStartAccount { get; set; }
        public string? FsPaidBalance { get; set; }
        public string? FsTrnFeeBalance { get; set; }
        public string? FsSCBalance { get; set; }
        public string? FsDlyFeeBalance { get; set; }
        public string? FsOtherFeeBalance { get; set; }
        public string? FreshStrtLetter1 { get; set; }
        public string? FreshStrtLetter2 { get; set; }
        public string? FreshStrtLetter3 { get; set; }
        public string? FreshStrtLetter4 { get; set; }
        public string? FreshStrtLetter5 { get; set; }
        public string? FreshStrtLetter6 { get; set; }
        public string? FreshStrtLetter7 { get; set; }
        public string? FreshStrtLetter8 { get; set; }
        public string? FreshStrtLetter9 { get; set; }
        public string? FsForceLetter { get; set; }
        public string? FsLetterToday { get; set; }
        public string? ExtraPrincip { get; set; }
        public string? RtChgDayOfMonth { get; set; }
        public string? AddressIndicator { get; set; }
        public string? PaymentRecalcDate { get; set; }
        public string? PmtCalcDayOfMth { get; set; }
        public string? PaymentRecalcFreq { get; set; }
        public string? RateChgNoticeTdy { get; set; }
        public string? PmtChgNoticeTdy { get; set; }
        public string? DatePriorIntPdTo { get; set; }
        public string? BegMoIntPdToDt { get; set; }
        public string? PrePayPnltyExpDt { get; set; }
        public string? MultipleNotices { get; set; }
        public string? NonAccrualIenc { get; set; }
        public string? AcctLevelMinInt { get; set; }
        public string? MinIntAmount { get; set; }
        public string? SweepPaysExempt { get; set; }
        public string? FreezeAdvances { get; set; }
        public string? TotalHoldAm { get; set; }
        public string? YtdReTaxes { get; set; }
        public string? MinimumBillingAmt { get; set; }
        public string? LoanFeesAny { get; set; }
        public string? GLPrincipalBal { get; set; }
        public string? GLIencAmou { get; set; }
        public string? _416ApplyPrincipal { get; set; }
        public string? CycleStatement { get; set; }
        public string? RecalculateP { get; set; }
        public string? DtArmRtChgNotice { get; set; }
        public string? DwellingIndicator { get; set; }
        public string? EstimatedArmBal { get; set; }
        public string? DebtRestructure { get; set; }
        public string? CollValueCalculatd { get; set; }
        public string? CollValueManual { get; set; }
        public string? CurrentLtvRatio { get; set; }
        public string? UnsecuredLoan { get; set; }
        public string? PerilInsPo { get; set; }
        public string? LifeInsPol { get; set; }
        public string? DueDteLifePrem { get; set; }
        public string? OrigDivisio { get; set; }
        public string? SecByResComMtg { get; set; }
        public string? CashSecurity { get; set; }
        public string? DueDateMoto { get; set; }
        public string? ValuePerilIns { get; set; }
        public string? ValueLifeIns { get; set; }
        public string? ValueMotorIns { get; set; }
        public string? DateLstEvaluation { get; set; }
        public string? ValuationReport { get; set; }
        public int LoanId { get; set; }
    }
}
