using System;
using System.Collections.Generic;

namespace Standing_Order_Vat_App.DAL.GB_Register
{
    public partial class Sav
    {
        public string? AccountNumber { get; set; }
        public string? CurrentBalance { get; set; }
        public string? MemoBalance { get; set; }
        public string? CtdAverageBalanceYtd { get; set; }
        public string? CtdLowBalance { get; set; }
        public string? LastStmtBalance { get; set; }
        public string? DateLastWithdrawal { get; set; }
        public string? DateLastDeposit { get; set; }
        public string? DateLastCycled { get; set; }
        public string? TypeCode { get; set; }
        public string? ClassCode { get; set; }
        public string? CtdDebits { get; set; }
        public string? CtdCredits { get; set; }
        public string? InterestRate { get; set; }
        public string? ServiceChargeCode { get; set; }
        public string? CorrespondingAcct { get; set; }
        public string? StmtRequestCode { get; set; }
        public string? CycleCode { get; set; }
        public string? StatementMessCode { get; set; }
        public string? InterestEarned { get; set; }
        public string? LastInterest { get; set; }
        public string? YtdInterest { get; set; }
        public string? LastWDAmou { get; set; }
        public string? LastDeposit { get; set; }
        public string? PrevStmtBalance { get; set; }
        public string? DatePrevStatement { get; set; }
        public string? YtdServiceCharge { get; set; }
        public string? YtdAverageBalanceYtd { get; set; }
        public string? UnpostToday { get; set; }
        public string? RateCode { get; set; }
        public string? MtdWithdrawals { get; set; }
        public string? _1DayFloat { get; set; }
        public string? _2DayFloat { get; set; }
        public string? _3DayFloat { get; set; }
        public string? AggregateFloatLstStmt { get; set; }
        public string? LowCollBalance { get; set; }
        public string? HighBalanceAmount { get; set; }
        public string? TransferToType { get; set; }
        public string? TransferToAccount { get; set; }
        public string? LowBalanceAmount { get; set; }
        public string? TransferFromType { get; set; }
        public string? AcctToTrnsfrFrom { get; set; }
        public string? AcctForInterest { get; set; }
        public string? AcctTypeForIntr { get; set; }
        public string? TransferOutAmount { get; set; }
        public string? TransferSerChgIn { get; set; }
        public string? TransferSerChgOut { get; set; }
        public string? DateIntLastPaid { get; set; }
        public string? YtdDebitCount { get; set; }
        public string? YtdCreditCount { get; set; }
        public string? AggregateBalance { get; set; }
        public string? AggregateFlo { get; set; }
        public string? LowBalance { get; set; }
        public string? LowCollectedBal { get; set; }
        public string? DebitsSinceSC { get; set; }
        public string? CreditsSinceSC { get; set; }
        public string? DateLastServChg { get; set; }
        public string? DatePrevSerCharge { get; set; }
        public string? DiscountOnSC { get; set; }
        public string? _45DayFloat { get; set; }
        public string? _610DayFloa { get; set; }
        public string? _1115DayFloat { get; set; }
        public string? Over15DayF { get; set; }
        public string? AtmAccountCode { get; set; }
        public string? EarlyWDPenalty { get; set; }
        public string? MtdAggregateBal { get; set; }
        public string? USEquivalent { get; set; }
        public string? ComtelBalance { get; set; }
        public string? AccrInt1st { get; set; }
        public string? AccrInt2nd { get; set; }
        public string? PassbookDate { get; set; }
        public string? PassbookBalance { get; set; }
        public string? AggDrsSince { get; set; }
        public string? Autoclose { get; set; }
        public string? ExemptChargeback { get; set; }
        public string? JanuaryAvgBal { get; set; }
        public string? FebruaryAvgBal { get; set; }
        public string? MarchAvgBal { get; set; }
        public string? AprilAvgBal { get; set; }
        public string? MayAvgBal { get; set; }
        public string? JuneAvgBal { get; set; }
        public string? JulyAvgBal { get; set; }
        public string? AugustAvgBal { get; set; }
        public string? SeptemberAvgBal { get; set; }
        public string? OctoberAvgBal { get; set; }
        public string? NovemberAvgBal { get; set; }
        public string? DecemberAvgBal { get; set; }
        public string? AggODLedgerBal { get; set; }
        public string? AggODCollBal { get; set; }
        public string? OpeningDepA { get; set; }
        public string? ClubDenomAmount { get; set; }
        public string? PrevServChgCode { get; set; }
        public string? AggBalSinLstInt { get; set; }
        public string? AggFltSinL { get; set; }
        public string? AggOdCollLstInt { get; set; }
        public string? AggOdBalLstInt { get; set; }
        public string? DatePrevIntPymt { get; set; }
        public string? AmtIntErnL { get; set; }
        public string? InterestPaid { get; set; }
        public string? ServChargeAssessed { get; set; }
        public string? PreviousCycleDate { get; set; }
        public string? AtmWDSinLstSC { get; set; }
        public string? ForeignAtmWD { get; set; }
        public string? TotalInclearings { get; set; }
        public string? CurrentViolation { get; set; }
        public string? ViolationHistory { get; set; }
        public string? ExemptForAtmSC { get; set; }
        public string? PrevExcessViol { get; set; }
        public string? DsiImageHorzPage { get; set; }
        public string? DsiImageVerImage { get; set; }
        public string? DsiImagePgeFmt { get; set; }
        public string? DsiImageFrBack { get; set; }
        public string? PrintDebitsCredit { get; set; }
        public string? QtdHighBalance { get; set; }
        public string? QtdInterest { get; set; }
        public string? CtdAverageBalance { get; set; }
        public string? CtdAverageF { get; set; }
        public string? YtdAverageBalance { get; set; }
        public string? AvailableBalance { get; set; }
        public string? StopPyNoticeFlag { get; set; }
        public string? StopPyAutoChgFlg { get; set; }
        public string? NumberAtmWDMtd { get; set; }
        public string? ForeignAtmWDMtd { get; set; }
        public string? NumberAtmWDYtd { get; set; }
        public string? ForeignAtmWDYtd { get; set; }
        public string? NbrAtmWDPriorYr { get; set; }
        public string? FrnAtmWDPrYr { get; set; }
        public string? AtmCrSinceSerChg { get; set; }
        public string? FrAtmCrSncSerCh { get; set; }
        public string? AtmCreditsMtd { get; set; }
        public string? ForeignAtmCrMtd { get; set; }
        public string? AtmCreditsYtd { get; set; }
        public string? ForeignAtmCrYtd { get; set; }
        public string? AtmCrPriorYear { get; set; }
        public string? FrgnAtmCrPrYear { get; set; }
        public string? UncollectedBalance { get; set; }
        public string? PriorDayUncollBal { get; set; }
        public string? CshMgmt2nd { get; set; }
        public string? CshMgmt2ndToAcct { get; set; }
        public string? CshMgt2ndFromTyp { get; set; }
        public string? CshMgt2ndFrmAcct { get; set; }
        public string? CshMgmtRepoFlag { get; set; }
        public string? CshMgtCollBalFlg { get; set; }
        public string? InterestDispCode { get; set; }
        public string? AchRoutingNumber { get; set; }
        public string? AchTransactionCode { get; set; }
        public string? AchAccountNumber { get; set; }
        public string? StmtSrtPrAcctFlg { get; set; }
        public string? ServiceChgWaiveCd { get; set; }
        public string? SerChrgWaiveDate { get; set; }
        public string? SerChgsWaivedYtd { get; set; }
        public string? SerChgsWaiv { get; set; }
        public string? SChgsReversedYtd { get; set; }
        public string? SChgsReversedPyr { get; set; }
        public string? PassbookFlag { get; set; }
        public string? TotalHoldAm { get; set; }
        public string? DatalinkMtdVceInq { get; set; }
        public string? DatalinkYtdVceInq { get; set; }
        public string? CollectedBalance { get; set; }
        public string? MultipleStatements { get; set; }
        public string? DateLstStmPrinted { get; set; }
        public string? FraudAlertFlag { get; set; }
        public string? OdNsfChgYtd { get; set; }
        public string? OdNsfChgPrvYear { get; set; }
        public string? _12MnthAverageBal { get; set; }
        public string? IncludeAchIndId { get; set; }
        public string? AchPositivePay { get; set; }
        public string? InterestRateAdj { get; set; }
        public string? UseAchFilters { get; set; }
        public string? WaiveWireFee { get; set; }
        public string? TransferInAmount { get; set; }
        public string? DailyWireLi { get; set; }
        public string? BeginningBalToday { get; set; }
        public string? ODChgsThisCycle { get; set; }
        public string? RetChgsThisCycle { get; set; }
        public string? ODChargesYtd { get; set; }
        public string? ReturnItemChgsYtd { get; set; }
        public string? PriorYrRegDdOD { get; set; }
        public string? PriorYrRetItmChg { get; set; }
        public string? SuppressNsfNotice { get; set; }
        public string? ExmpODNsfCharge { get; set; }
        public string? StatementFormat { get; set; }
        public string? ConsecutiveDaysOd { get; set; }
        public string? ChargedOff { get; set; }
        public string? AmountChargedOff { get; set; }
        public string? DateChargedOff { get; set; }
        public string? ChargeOffRecovery { get; set; }
        public string? DateOfRecovery { get; set; }
        public string? ExemptAutoChgOff { get; set; }
        public string? YtdOverdrawnDays { get; set; }
        public string? LastYearOdDays { get; set; }
        public string? WaiveAtmUsageCr { get; set; }
        public string? AtmUsageCreditCtd { get; set; }
        public string? Cyc12IntErn1231 { get; set; }
        public int SavId { get; set; }
    }
}
