using System;
using System.Collections.Generic;

namespace Standing_Order_Vat_App.DAL.SKNAB
{
    public partial class Upr10214
    {
        public string Employid { get; set; } = null!;
        public decimal Pyytdarr1 { get; set; }
        public decimal Pyytdarr2 { get; set; }
        public decimal Pyytdarr3 { get; set; }
        public decimal Pyytdarr4 { get; set; }
        public decimal Pyytdarr5 { get; set; }
        public decimal Pyytdarr6 { get; set; }
        public decimal Pyytdarr7 { get; set; }
        public decimal Pyytdarr8 { get; set; }
        public decimal Pyytdarr9 { get; set; }
        public decimal Pyytdarr10 { get; set; }
        public decimal Pyytdarr11 { get; set; }
        public decimal Pyytdarr12 { get; set; }
        public decimal Pyytdarr13 { get; set; }
        public decimal Pyytdarr14 { get; set; }
        public decimal Pyytdarr15 { get; set; }
        public decimal Pyytdarr16 { get; set; }
        public decimal Pyytdarr17 { get; set; }
        public decimal Pyytdarr18 { get; set; }
        public decimal Pyytdarr19 { get; set; }
        public decimal Pyytdarr20 { get; set; }
        public decimal Pyytdarr21 { get; set; }
        public decimal Pyytdarr22 { get; set; }
        public decimal Pyytdarr23 { get; set; }
        public decimal Pyytdarr24 { get; set; }
        public decimal Pyytdarr25 { get; set; }
        public decimal Damytdar1 { get; set; }
        public decimal Damytdar2 { get; set; }
        public decimal Damytdar3 { get; set; }
        public decimal Damytdar4 { get; set; }
        public decimal Damytdar5 { get; set; }
        public decimal Damytdar6 { get; set; }
        public decimal Damytdar7 { get; set; }
        public decimal Damytdar8 { get; set; }
        public decimal Damytdar9 { get; set; }
        public decimal Damytdar10 { get; set; }
        public decimal Damytdar11 { get; set; }
        public decimal Damytdar12 { get; set; }
        public decimal Damytdar13 { get; set; }
        public decimal Damytdar14 { get; set; }
        public decimal Damytdar15 { get; set; }
        public decimal Damytdar16 { get; set; }
        public decimal Damytdar17 { get; set; }
        public decimal Damytdar18 { get; set; }
        public decimal Damytdar19 { get; set; }
        public decimal Damytdar20 { get; set; }
        public decimal Damytdar21 { get; set; }
        public decimal Damytdar22 { get; set; }
        public decimal Damytdar23 { get; set; }
        public decimal Damytdar24 { get; set; }
        public decimal Damytdar25 { get; set; }
        public decimal Bamytdar1 { get; set; }
        public decimal Bamytdar2 { get; set; }
        public decimal Bamytdar3 { get; set; }
        public decimal Bamytdar4 { get; set; }
        public decimal Bamytdar5 { get; set; }
        public decimal Bamytdar6 { get; set; }
        public decimal Bamytdar7 { get; set; }
        public decimal Bamytdar8 { get; set; }
        public decimal Bamytdar9 { get; set; }
        public decimal Bamytdar10 { get; set; }
        public decimal Bamytdar11 { get; set; }
        public decimal Bamytdar12 { get; set; }
        public decimal Bamytdar13 { get; set; }
        public decimal Bamytdar14 { get; set; }
        public decimal Bamytdar15 { get; set; }
        public decimal Bamytdar16 { get; set; }
        public decimal Bamytdar17 { get; set; }
        public decimal Bamytdar18 { get; set; }
        public decimal Bamytdar19 { get; set; }
        public decimal Bamytdar20 { get; set; }
        public decimal Bamytdar21 { get; set; }
        public decimal Bamytdar22 { get; set; }
        public decimal Bamytdar23 { get; set; }
        public decimal Bamytdar24 { get; set; }
        public decimal Bamytdar25 { get; set; }
        public decimal Statxytd1 { get; set; }
        public decimal Statxytd2 { get; set; }
        public decimal Statxytd3 { get; set; }
        public decimal Statxytd4 { get; set; }
        public decimal Statxytd5 { get; set; }
        public decimal Statxytd6 { get; set; }
        public decimal Statxytd7 { get; set; }
        public decimal Statxytd8 { get; set; }
        public decimal Statxytd9 { get; set; }
        public decimal Statxytd10 { get; set; }
        public decimal Statxytd11 { get; set; }
        public decimal Statxytd12 { get; set; }
        public decimal Statxytd13 { get; set; }
        public decimal Statxytd14 { get; set; }
        public decimal Statxytd15 { get; set; }
        public decimal Statxytd16 { get; set; }
        public decimal Statxytd17 { get; set; }
        public decimal Statxytd18 { get; set; }
        public decimal Statxytd19 { get; set; }
        public decimal Statxytd20 { get; set; }
        public decimal Statxytd21 { get; set; }
        public decimal Statxytd22 { get; set; }
        public decimal Statxytd23 { get; set; }
        public decimal Statxytd24 { get; set; }
        public decimal Statxytd25 { get; set; }
        public decimal Lcltxytd1 { get; set; }
        public decimal Lcltxytd2 { get; set; }
        public decimal Lcltxytd3 { get; set; }
        public decimal Lcltxytd4 { get; set; }
        public decimal Lcltxytd5 { get; set; }
        public decimal Lcltxytd6 { get; set; }
        public decimal Lcltxytd7 { get; set; }
        public decimal Lcltxytd8 { get; set; }
        public decimal Lcltxytd9 { get; set; }
        public decimal Lcltxytd10 { get; set; }
        public decimal Lcltxytd11 { get; set; }
        public decimal Lcltxytd12 { get; set; }
        public decimal Lcltxytd13 { get; set; }
        public decimal Lcltxytd14 { get; set; }
        public decimal Lcltxytd15 { get; set; }
        public decimal Lcltxytd16 { get; set; }
        public decimal Lcltxytd17 { get; set; }
        public decimal Lcltxytd18 { get; set; }
        public decimal Lcltxytd19 { get; set; }
        public decimal Lcltxytd20 { get; set; }
        public decimal Lcltxytd21 { get; set; }
        public decimal Lcltxytd22 { get; set; }
        public decimal Lcltxytd23 { get; set; }
        public decimal Lcltxytd24 { get; set; }
        public decimal Lcltxytd25 { get; set; }
        public decimal Grswgytd { get; set; }
        public decimal Ntwgsytd { get; set; }
        public decimal Ficawytd { get; set; }
        public decimal Fcassytd { get; set; }
        public decimal Ficamytd { get; set; }
        public decimal Fdwdgytd { get; set; }
        public decimal Swhdgytd { get; set; }
        public decimal Lcwhgytd { get; set; }
        public int DexRowId { get; set; }
    }
}
